auth_enabled: false

server:
  http_listen_port: 3100
  grpc_server_max_recv_msg_size: 104857600
  grpc_server_max_send_msg_size: 104857600

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  chunk_idle_period: 2h
  chunk_target_size: 1536000
  max_chunk_age: 2h

schema_config:
  configs:
    - from: 2020-02-25
      store: boltdb
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb:
    directory: /tmp/loki/index

limits_config:
  retention_period: 48h
  enforce_metric_name: false
  reject_old_samples: false
  # reject_old_samples_max_age: 168h
  ingestion_rate_mb: 1024
  ingestion_burst_size_mb: 1024
  per_stream_rate_limit: "3MB"
  per_stream_rate_limit_burst: "10MB"
  max_global_streams_per_user: 10000
  max_global_streams_per_user: 0
  # max_streams_per_user: 1000000000000000
  # max_global_streams_per_user: 0


# chunk_store_config:
#   max_chunk_age: 864000000000